// <auto-generated />

namespace MyRentals.Persistence.Migrations
{
    using System;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Infrastructure;

    [DbContext(typeof(MyRentalsContext))]
    partial class MyRentalsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("MyRentals.Domain.StorageModels.Apartment", b =>
                {
                    b.Property<ulong>("ApartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FloorArea")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRented")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Lat")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Lon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfRooms")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PricePerMonth")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("RealtorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ApartmentId");

                    b.HasIndex("RealtorId");

                    b.ToTable("Apartments");
                });

            modelBuilder.Entity("MyRentals.Domain.StorageModels.Client", b =>
                {
                    b.Property<ulong>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("MyRentals.Domain.StorageModels.Realtor", b =>
                {
                    b.Property<ulong>("RealtorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RealtorEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RealtorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RealtorId");

                    b.ToTable("Realtors");
                });

            modelBuilder.Entity("MyRentals.StorageModels.Apartment", b =>
                {
                    b.HasOne("MyRentals.Domain.StorageModels.Realtor", null)
                        .WithMany()
                        .HasForeignKey("RealtorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
